### ISSUE TITLE
MacOS terminal stops echoing characters

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#11647]
I created a brand new project with "dotnet new avalonia.app".  After either "dotnet build" or "dotnet run", characters stop echoing to the screen.  Characters are being sent from the keyboard to the terminal though.  See screenshot:
![Screen Shot 2023-06-04 at 7 11 02 AM](https://github.com/AvaloniaUI/Avalonia/assets/62225294/ea091490-5300-4df0-a1a8-d88659617e01)

MacOS: 10.15.7
dotnet version is 7, but the target framework is "net6.0".  I have version 6.0.408 installed.

**Comment by cpacejo** [comment]
This occurs on Linux (Debian / Gnome Terminal) also, with preview8 and rc1.1, but not preview7 or preview6.

**Comment by kekekeks** [comment]
Please check with RC2, we've changed the way we are spawning processes from msbuild task

**Comment by mrj001** [comment]
The command
`$ dotnet new install Avalonia.Templates::11.0.0-rc2.2`
resulted in the following:
> The following template packages will be installed:
>    Avalonia.Templates::11.0.0-rc2.2
> 
> Avalonia.Templates (version 0.10.24) is already installed, it will be replaced with version 11.0.0-rc2.2.
> Avalonia.Templates::0.10.24 was successfully uninstalled.
> Warning: Avalonia.Templates::11.0.0-rc2.2 is not found in NuGet feeds https://api.nuget.org/v3/index.json.
> Avalonia.Templates::11.0.0-rc2.2 could not be installed, the package does not exist.
> 
> For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

I tried changing the version in the .csproj to the 11.0.0-rc2.2 and updating the theme.  I'm still getting this on build:

> .../Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/test.MainWindow.g.cs(19,21): error CS0111: Type 'MainWindow' already defines a member called 'InitializeComponent' with the same parameter types [/Users/mj/Documents/develop/tmp/test/test.csproj]
> 
> Build FAILED.
> 

I'm afraid I don't have time to pursue this further at the moment.  Perhaps later today.  Where can I get the 11.0 templates?  Alternatively, how do I get past the above build error with the 0.10 templates?

**Comment by mrj001** [comment]
I was wrong about the time....  Other people weren't ready.

I just had to delete the reference to `XamlNameReferenceGenerator` from the .csproj file.

After "dotnet build" and "dotnet run", the characters still echo to the terminal.

Version: 11.0.0-rc2.2

**Comment by cpacejo** [comment]
11.0.0-rc2.2 seems to have remedied this for me, thanks!  Only tested a few builds so far (the original issue was intermittent) but will report back after a few days' usage.

**Comment by cpacejo** [comment]
Have not encountered the issue again after a few days of working with rc2.2.
