### ISSUE TITLE
Updating project 0.10.0 to 11.0.0preview5

### ISSUE THREAD

**Issue by Wael1231** [AvaloniaUI/Avalonia#11099]
hey i am updating old project of avalonia and when i update to 11.0.0preview5 i get some error : 
 Error 1 : DeferredRenderer' Not found (specific where the emplacement)
Error 2 : IControl' Not Found
Error 3 : 'ViewLocator' does not implement the interface member 'ITemplate<object?, Control?>. Build(object?)'. 'ViewL
ocator. Build(object)' cannot implement 'ITemplate<object?, Control?>. Build(object?)', because it does not have the t
corresponding return ype 'Control'

**Comment by timunie** [comment]
Please read breaking changes wiki.

**Comment by Wael1231** [comment]
can specific please

**Comment by MonsieurTib** [comment]
@Wael1231 maybe this ? https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes

**Comment by Wael1231** [comment]
there not about DeferredRenderer equivalent ?

**Comment by timunie** [comment]
> there not about DeferredRenderer equivalent ?

No we have now a faster CompositeRenderer

**Comment by Wael1231** [comment]
i din'd find CompositeRenderer in Avalonia ?

**Comment by timunie** [comment]
Why exactly do you need it? Normally, you don't access the renderer directly.

**Comment by Wael1231** [comment]
for HarmonyPatch

**Comment by maxkatz6** [comment]
DeferredRenderer with whole old rendered scene was removed.
Composition renderer works in a different way. What exact APIs have you used from DeferredRenderer?

**Comment by Wael1231** [comment]
i will send you the code and see  

Code : https://github.com/polusgg/mod-bepinex-launcher/blob/main/ClientLauncher/MonkePatches/DeferredRenderer_Patches.cs

**Comment by maxkatz6** [comment]
I don't quite understand, what this code does, and why exactly you need to patch Avalonia. Needless to say, we can't support framework patching.

Direct replacement is https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs#L19, but it also comes with lots of changes in other APIs.

**Comment by timunie** [comment]
@Wael1231 if you're trying to solve an actual issue with the patches, consider to file a proper issue and in the best case also a PR that solves your issues instead. Better for both sides I guess.
