### ISSUE TITLE
cs0111 error with 11.0.0-preview6

### ISSUE THREAD

**Issue by KluDev** [AvaloniaUI/Avalonia#10740]
**To Reproduce**

1. Create a new App dotnet new avalonia.mvvm -o DotTest -n DotTest
2. Change the PackageReference to 11.0.0-preview6 for all packages 
3. Do dotnet run
4. You will get the following error
....\DotTest\Avalonia.NameGenerator\Avalonia.NameGenerator.AvaloniaNameSourceGenerator\DotTest.Views.MainWindow.g.cs(19,21): error CS0111: Type 'MainWindow' already defines a member called 'InitializeComponent' with the same parameter types

5. Change the PackageReference to 11.0.0-preview5 for all packages
6. Do donet run
7. No error 

How can I fix this error?

**Comment by timunie** [comment]
@KluDev please read through the breaking changes page when updating from 0.10 ► 11.0 preview

see: https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#010--110
