### ISSUE TITLE
Missing `AppBuilder` with 0.9.8 release

### ISSUE THREAD

**Issue by define-private-public** [AvaloniaUI/Avalonia#3802]
I wanted to try out the new release for a spin.  I had a project that I made with 0.9.0, that was building fine.  When I updated to 0.9.8, I was getting this build error:

```
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 45.44 ms for /home/ben/Projects/AvaloniaSamples/BassoonJukebox/BassoonJukebox.csproj.
Program.cs(18,23): error CS0246: The type or namespace name 'AppBuilder' could not be found (are you missing a using directive or an assembly reference?) [/home/ben/Projects/AvaloniaSamples/BassoonJukebox/BassoonJukebox.csproj]

Build FAILED.

Program.cs(18,23): error CS0246: The type or namespace name 'AppBuilder' could not be found (are you missing a using directive or an assembly reference?) [/home/ben/Projects/AvaloniaSamples/BassoonJukebox/BassoonJukebox.csproj]
    0 Warning(s)
    1 Error(s)
```

When I tried 0.9.7 instead, it build (and ran) fine.

**Comment by phillvancejr** [comment]
Have the same issue on MacOS 10.14

**Comment by FoggyFinder** [comment]
> I wanted to try out the new release for a spin. I had a project that I made with 0.9.0, that was building fine. When I updated to 0.9.8, I was getting this build error:

Make sure you're using .net 3.1 and not the previous one.

**Comment by phillvancejr** [comment]
I'm currently using 3.1.2

**Comment by danwalmsley** [comment]
Sorry about this, we messed up the release. `0.9.9` is now available with this fixed.
