### ISSUE TITLE
androidx.core:core-splashscreen:1.2.0.3 Compilation error

### ISSUE THREAD

**Issue by Ly2JR** [AvaloniaUI/Avalonia#21765]
### Describe the bug

After upgrading from version 1.2.0.2 to 1.2.0.3, there's an error compiling the Android project

“Type androidx.core.animation.AnimatorKt$addListener$2 is defined multiple times:”

4>MSBUILD : java.exe error JAVA0000: Error in obj\Debug\net10.0-android36.0\lp\74\jl\classes.jar:androidx/core/animation/AnimatorKt$addListener$1.class:
4>MSBUILD : java.exe error JAVA0000: Type androidx.core.animation.AnimatorKt$addListener$1 is defined multiple times: obj\Debug\net10.0-android36.0\lp\74\jl\classes.jar:androidx/core/animation/AnimatorKt$addListener$1.class, obj\Debug\net10.0-android36.0\lp\80\jl\classes.jar:androidx/core/animation/AnimatorKt$addListener$1.class
4>MSBUILD : java.exe error JAVA0000: Compilation failed
4>MSBUILD : java.exe error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net10.0-android36.0\lp\74\jl\classes.jar
4>MSBUILD : java.exe error JAVA0000: androidx/core/animation/AnimatorKt$addListener$1.class
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:131)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.main(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:5)
4>MSBUILD : java.exe error JAVA0000: Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net10.0-android36.0\lp\74\jl\classes.jar:androidx/core/animation/AnimatorKt$addListener$1.class
4>MSBUILD : java.exe error JAVA0000: 	at Version.fakeStackEntry(Version_8.11.18.java:0)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.P.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:1)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:82)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:32)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:31)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.b(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:2)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:30)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.b(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:23)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:28)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:118)
4>MSBUILD : java.exe error JAVA0000: 	... 1 more
4>MSBUILD : java.exe error JAVA0000: Caused by: com.android.tools.r8.internal.g: Type androidx.core.animation.AnimatorKt$addListener$1 is defined multiple times: obj\Debug\net10.0-android36.0\lp\74\jl\classes.jar:androidx/core/animation/AnimatorKt$addListener$1.class, obj\Debug\net10.0-android36.0\lp\80\jl\classes.jar:androidx/core/animation/AnimatorKt$addListener$1.class
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.yg0.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:21)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.O80.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:54)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.O80.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:10)
4>MSBUILD : java.exe error JAVA0000: 	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.O80.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:6)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.graph.z4$a.c(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:6)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:56)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:12)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:33)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.d(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:20)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.c(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:8)
4>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.xv.a(R8_8.11.18_94248c9a6fd57686ded562f231d18f14e8923ad1fe977e99b974a9bf901c8a48:28)
4>MSBUILD : java.exe error JAVA0000: 	... 6 more
4>MSBUILD : java.exe error JAVA0000: 目录“obj\Debug\net10.0-android36.0\lp\74”来自“androidx.core.core.aar”。
4>MSBUILD : java.exe error JAVA0000: 目录“obj\Debug\net10.0-android36.0\lp\80”来自“androidx.core.core-ktx.aar”。

### To Reproduce

1.Create a cross-platform project using Avalonia
2.upgrade Xamarin.AndroidX.Core.SplashScreen to 1.2.0.3
3.and then compile the whole project

https://github.com/Ly2JR/Avalonia12.1.0.git

4.downgrading to 1.2.0.2 lets it compile successfully

### Expected behavior

Compilation successful

### Avalonia version

12.1.0

### OS

Android

**Comment by Ly2JR** [comment]
I installed androidx.core.core-ktx:1.19.1 separately, and it compiled successfully.
